### PR TITLE
Ensure there are no double trailing slashes

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by hadley** [comment]
Do you remember what this was for?

**Comment by maelle** [comment]
I vaguely remember seeing double slashes in a package like bslib (either bslib or a package authored by the same people) :thinking: Not happy I did not make a note of it.

**Comment by maelle** [comment]
Related https://github.com/r-lib/pkgdown/pull/1526 (in the sense that maybe downlit had similar problems somewhere)

**Comment by hadley** [comment]
Ok, let's leave it for now and if we see it again we can make a test.

**Pull request closed without merging**
