### PR TITLE
Add pkgdown URL to DESCRIPTION

### PR DESCRIPTION
**Pull request by maelle**
ICYMI this can be useful :joy:

### CODE REVIEW

**Comment by maelle** [comment]
(this will break tests in my PR #40 so I'll need to edit them :woman_shrugging: )

**Comment by hadley** [comment]
Thanks! I made a note that we should automate this in https://github.com/r-lib/usethis/issues/224

**Comment by maelle** [comment]
could pkgdown itself also help with that? if it detects an url in the pkgdown config and can't find it in DESCRIPTION, maybe it could print a warning?

**Comment by hadley** [comment]
That feels out of scope for pkgdown to me, since it's not generally in the business of warning you about workflow issues.

**Pull request merged**
